// Orchestrates all content generation and writes browser-ready data files into js/data/.
// Each emitted file is a classic <script> that augments a global `MQ` namespace,
// so the game runs by simply opening index.html (no server / module / CORS needed).
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { makeRng } from './lib/rng.js';
import { TYPES, TYPE_CHART } from './lib/types.js';
import { generateMoves } from './lib/gen-moves.js';
import { generateItems } from './lib/gen-items.js';
import { generateMonsters } from './lib/gen-monsters.js';
import { generateWorld } from './lib/gen-world.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DATA = join(ROOT, 'js', 'data');
mkdirSync(DATA, { recursive: true });

const SEED = 0x5eed1234;

function emit(file, key, value) {
  const body = `// AUTO-GENERATED by tools/generate.js — do not edit by hand.\n` +
    `window.MQ = window.MQ || {};\n` +
    `window.MQ.${key} = ${JSON.stringify(value, null, 1)};\n`;
  writeFileSync(join(DATA, file), body, 'utf8');
  return body.length;
}

console.log('Generating content with seed', SEED.toString(16), '...');

// --- Types ---
emit('types.js', 'types', TYPES);
emit('typechart.js', 'typeChart', TYPE_CHART);

// --- Moves ---
const moves = generateMoves();
emit('moves.js', 'moves', moves);

// --- Items ---
const items = generateItems();
emit('items.js', 'items', items);

// --- Monsters (shares one RNG stream) ---
const monRng = makeRng(SEED);
const { monsters, legendaryDex, mythicalDex, regions } = generateMonsters(monRng);
emit('monsters.js', 'monsters', monsters);
emit('special.js', 'special', { legendaryDex, mythicalDex, regions });

// --- World: maps, encounters, NPCs, trainers ---
const worldRng = makeRng(SEED ^ 0x1234);
const world = generateWorld(worldRng, { monsters, regions, items, legendaryDex, mythicalDex });
emit('maps.js', 'maps', world.maps);
emit('npcs.js', 'npcs', world.npcs);
emit('encounters.js', 'encounters', world.encounters);
emit('tiles.js', 'tiles', world.tiles);
emit('tileenum.js', 'tileEnum', world.tileEnum);

// --- Report ---
const byCat = {};
for (const m of monsters) byCat[m.category] = (byCat[m.category] || 0) + 1;
const withEvo = monsters.filter(m => m.evolution).length;
console.log('\n=== Generation summary ===');
console.log('Types:        ', TYPES.length);
console.log('Moves:        ', moves.length);
console.log('Items:        ', items.length);
console.log('Monsters:     ', monsters.length, JSON.stringify(byCat));
console.log('  with evolution:', withEvo, '| legendary:', legendaryDex.length, '| mythical:', mythicalDex.length);
console.log('Maps:         ', world.maps.length);
console.log('NPCs:         ', world.npcs.length, `(trainers: ${world.npcs.filter(n => n.kind === 'trainer').length})`);
console.log('Encounter tbl:', Object.keys(world.encounters).length);
console.log('\nData written to', DATA);
